server:
  port: ":8080"

database:
  user: "abhishek"
  password: "KksT585$"
  dbname: "youtube_videos"
  host: "20mis0158_backend-db-1"
  port: "5432"

youtube:
  api_keys:
    - "AIzaSyBKwrwtkN-syL-9wSZBoZ1v3Qz0NBjKdp8"
    - "AIzaSyCbyS9twmUpbkfH8GN6vIZklA4CnnO7-LA"
    - "AIzaSyARTor_ohGOcjSpWxuML7zas7z3Uv1TOKg"
    - "AIzaSyCjyAu-GZ023w1SCW6CP8MrLggAD0IDGDI"
    - "AIzaSyAMdJW9ddHQEHPqgBaGLc3bLkrKTC0Ex4w"
    - "AIzaSyCa2omcrZIMQaJSdjukFgV4eEIaNdYIzC4"
    - "AIzaSyDRs6Sfno2jXJWo0QOQCwBz2TIs9PK_swg"
    - "AIzaSyBM4inA_lW7pSVkOUnFum45D-4b6-RGA80"
    - "AIzaSyCRRp7WG10RGv1XiPF0KuKVwPyH0gqAdaA"
    - "AIzaSyD4c2YW5SFuvpg4NogciUowGdxF_wygqf4"
  search_query: "music"
  fetch_interval_seconds: 2
