server:
  port: ":8080"

database:
  user: "abhishek"
  password: "fJomBjck74yooAnOeqdZF7hUbhAOXndl"
  dbname: "youtube_videos_lf49"
  host: "dpg-cqru6ndumphs73cqo98g-a"
  port: "5432"

youtube:
  api_keys:
    - "AIzaSyDnWbleoG7hj7eH1bx8LrwG0nOOz7O_Bsk
"
    - "AIzaSyDB5rr5mWdcd2HhY-Sgv8kD7Aa3AJHpBb8
"
    - "AIzaSyB0U9gRskWgR_roeicaNdfh1UgA8RtWCl8
"
    - "AIzaSyB6x2m-Ugl7khbWdqIQ3CHV-_zjX2UUTjk
"
    - "AIzaSyBo7nE8YCaKeZiyEsN6RNiiW-eTbUwnssA
"
    - "AIzaSyCUhxMQmZsCzUa7vwoBwEPpVbCOi53ZbYw
"
    - "AIzaSyCoXaw_YeFo-LV_1Vz5NeiIT0PHPEyBlDY
"
    - "AIzaSyCsDSzcsfITLgvMI9-s8O45g1Dq8oNU-Kg
"
    - "AIzaSyAmZuFc9rzX2s6s93TFZ0D7QCh27I2t-Yg
"
    - "AIzaSyDDFfOm759GxMvKByrdfRjNrL3gRPMtZvw
"
  search_query: "cricket"
  fetch_interval_seconds: 2
